version: '3'

services:

  hlds:
    container_name: counter-strike_server
    build: .
    restart: always
    environment:
      - PORT=27015
      - MAP=${CS_MAP}
      - MAXPLAYERS=${CS_MAXPLAYERS}
      - SV_LAN=0
    ports:
      - 27015:27015/udp
      - 27015:27015
    volumes:
      - /home/centos/lightsail-counterstrike/server.cfg:/hlds/cstrike/server.cfg

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /home/centos/duckdns/config:/config #optional
    restart: unless-stopped

