version: '3.7'

services:

#
# cs
# HLDS Counter Strike 1.6 Server
#
  cs:
    image: cs16ds/server:latest
    restart: always
    ports:
    - 27020:27020/udp
    - 27015:27015/udp
    - 26900:26900/udp
    - 27015:27015
    environment:
    - ADMIN_STEAM=0:1:1234566

