version: '3.7'

services:

#
# cs
# HLDS Counter Strike 1.6 Server
#
  cs:
    image: ggoulart/cs1.6-server-more-maps
    restart: always
    ports:
    - 27015:27015
    - 27015:27015/udp

#
# no-ip
# This is a simple Docker container for running the No-IP2 dynamic DNS update script. 
# It will keep your domain.ddns.net DNS alias up-to-date as your home IP changes.
#
  no-ip:
    image: coppit/no-ip
    container_name: noip
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/centos/noip:/config
      - /home/centos/lightsail-cs/noip.conf:/config/noip.conf
    environment:
      - PGID=1000 #optional
      - PUID=1000 #optional
